name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-versions: [3.10.4]
    steps:
      - uses: actions/checkout@v2
      - name: Installing Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python_versions}}
      - name: Installing dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Running mypy
        run: mypy .