name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        python-versions: [3.10.4, 3.10.5]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installing Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python_versions}}
      - name: Installing dependencies
        run:
          pip install -r requirements.txt